language: ruby
cache:
  - bundler
rvm:
  - "2.1.1"
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
script: 
  - RAILS_ENV=test bundle exec rake db:migrate
  - bundle exec rake db:test:prepare
  - bundle exec rspec spec
